grails-app/domain/com/unionbank/rwo/management/StatusB.groovy
package com.unionbank.rwo.management

class StatusB {

	String statusCd
	String description

	static hasMany = [gftMsgBs: GftMsgB,
	                  wireDataBs: WireDataB]

	static mapping = {
		id name: "statusCd", generator: "assigned"
		version false
		table "STATUS_B"
	}

	static constraints = {
		statusCd maxSize: 3
		description nullable: true, maxSize: 16
	}
}

grails-app/views/statusB/_form.gsp
// NOTHING to generate

grails-app/views/statusB/create.gsp
<%@ page import="com.unionbank.rwo.management.StatusB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'statusB.label', default: 'StatusB')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.create.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				
			
			<div class="block-800px center">

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info block-800px center">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${statusBInstance}">
				<bootstrap:alert class="alert-error block-800px center">
				<ul>
					<g:eachError bean="${statusBInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal" action="save" >
						<fieldset>
							<div class="control-group ">
								<label class="control-label" for="${statusBInstance?.id}">${statusBInstance?.id}</label>
								<div class="controls primary-key-id">
									${statusBInstance?.id}
								</div>
							</div>
							<f:all bean="statusBInstance"/>
							<div class="form-actions">
								<g:link class="list btn" action="list">
									<i class="icon-arrow-left"></i>
									<g:message code="default.button.cancel.label" default="Cancel" />
								</g:link>
								<button type="submit" class="btn btn-success">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.create.label" default="Create" />
								</button>
							</div>
						</fieldset>
					</g:form>
				</fieldset>
				</div>
			</div>

		</div>
	</body>
</html>

grails-app/views/statusB/edit.gsp
<%@ page import="com.unionbank.rwo.management.StatusB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'statusB.label', default: 'StatusB')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.edit.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				
			
			<div>
				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info block-800px center">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${statusBInstance}">
				<bootstrap:alert class="alert-error block-800px center">
				<ul>
					<g:eachError bean="${statusBInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal block-800px center" action="edit" id="${statusBInstance?.id}" >
						<g:hiddenField name="version" value="${statusBInstance?.version}" />
						<fieldset>
							<f:display bean="statusBInstance" property="keyName"/>					
							<f:all bean="statusBInstance" except="id,keyName"/>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary" name="_action_update">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.update.label" default="Update" />
								</button>
								<button type="submit" class="btn btn-danger" name="_action_delete" formnovalidate onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
									<i class="icon-trash icon-white"></i>
									<g:message code="default.button.delete.label" default="Delete" />
								</button>
								<g:link class="list btn" action="list">
									<i class="icon-arrow-left"></i>
									<g:message code="default.button.cancel.label" default="Cancel" />
								</g:link>
							</div>
						</fieldset>
					</g:form>
				</fieldset>
				</div>
			</div>
		</div>
	</body>
</html>

grails-app/views/statusB/list.gsp
<%@ page import="com.unionbank.rwo.management.StatusB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'statusB.label', default: 'StatusB')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.list.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info block-800px center">${flash.message}</bootstrap:alert>
				</g:if>
				<div class="table-responsive">
				<table class="table table-striped table-800px center intro-page-main-data">
					<thead>
						<tr class="intro-page-main-metadata">
						
							<g:sortableColumn property="statusCd" title="${message(code: 'statusB.statusCd.label', default: 'Status Cd')}" />
						
							<g:sortableColumn property="description" title="${message(code: 'statusB.description.label', default: 'Description')}" />
						
							<th class="pull-right">Operations</th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${statusBInstanceList}" var="statusBInstance">
						<tr>
						
							<td>${fieldValue(bean: statusBInstance, field: "statusCd")}</td>
						
							<td>${fieldValue(bean: statusBInstance, field: "description")}</td>
						
							<td class="link text-right intro-entity-button-functions">
									<g:link action="show"
										id="${statusBInstance.id}" class="btn btn-success btn-mini intro-entity-button-show">
										<i class="icon-search icon-white"></i><span class="hidden-phone"> Show</span>
									</g:link>
									 <g:link
										class="btn btn-primary btn-mini intro-entity-button-edit }" action="edit"
										id="${statusBInstance?.id}">
										<i class="icon-pencil icon-white"></i><span class="hidden-phone"> <g:message code="default.button.edit.label" default="Edit" /></span>
									</g:link> 
									<g:form class="form-inline display-inline" action="edit" id="${statusBInstance?.id}" >
										<g:hiddenField name="version" value="${statusBInstance?.version}" />
										<g:hiddenField name="id" value="${statusBInstance?.id}" />
										<button type="submit" class="btn btn-danger btn-mini intro-entity-button-delete" name="_action_delete" formnovalidate onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
											<i class="icon-trash icon-white"></i><span class="hidden-phone"> <g:message code="default.button.delete.label" default="Delete" /></span>
										</button>							
									</g:form>
							</td>
						</tr>
						
					</g:each>
					</tbody>
				</table>
				</div>
				<div class="pagination pagination-centered">
					<bootstrap:paginate total="${statusBInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

grails-app/views/statusB/revisions.gsp
<%@ page import="com.unionbank.rwo.management.StatusB" %>

<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'statusB.label', default: 'StatusB')}" />
		<title><g:message code="default.revisions.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.revisions.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn" id="entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				<div class="table-responsive">
				<table class="table table-striped center intro-page-main-data">
					<thead>
						<tr class="intro-page-main-metadata">

			            <g:sortableColumn property="revisionEntity.id" title="${message(code: 'envers.id.label', default: 'Rev id')}"/>
			
			            <g:sortableColumn property="revisionType" title="${message(code: 'envers.revisionType.label', default: 'Rev type')}"/>
			
			            <g:sortableColumn property="revisionEntity.revisionDate" title="${message(code: 'envers.revisionDate.label', default: 'Rev date')}"/>
			
			            <g:sortableColumn property="revisionEntity.currentUser" title="${message(code: 'envers.currentUser.label', default: 'Rev author')}"/>
						
						
						
						
							<g:sortableColumn property="statusCd" title="${message(code: 'statusB.statusCd.label', default: 'Status Cd')}" />
						
							<g:sortableColumn property="description" title="${message(code: 'statusB.description.label', default: 'Description')}" />
						
						</tr>
					</thead>
					<tbody>
					<g:each in="${statusBRevisionInstanceList}" var="statusBRevision">
						<tr>
					<td><g:fieldValue field="revisionEntity.id" bean="${statusBRevision}" /></td>
			
			                <td><g:fieldValue field="revisionType" bean="${statusBRevision}" /></td>
						
			                <td><g:fieldValue field="revisionEntity.revisionDate" bean="${statusBRevision}" /></td>
			
			                <td><g:fieldValue field="revisionEntity.currentUser" bean="${statusBRevision}" /></td>

						
							<td>${fieldValue(bean: statusBRevision, field: "statusCd")}</td>
						
							<td>${fieldValue(bean: statusBRevision, field: "description")}</td>
						

						</tr>
						
					</g:each>
					</tbody>
				</table>
				</div>
				<div class="pagination pagination-right">
					<bootstrap:paginate total="${statusBRevisionInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

grails-app/views/statusB/show.gsp
<%@ page import="com.unionbank.rwo.management.StatusB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'statusB.label', default: 'StatusB')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">

				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.show.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<dl class="block-800px center">
				
					<g:if test="${statusBInstance?.statusCd}">
						<dt><g:message code="statusB.statusCd.label" default="Status Cd" /></dt>
						
							<dd><g:fieldValue bean="${statusBInstance}" field="statusCd"/></dd>
						
					</g:if>
				
					<g:if test="${statusBInstance?.description}">
						<dt><g:message code="statusB.description.label" default="Description" /></dt>
						
							<dd><g:fieldValue bean="${statusBInstance}" field="description"/></dd>
						
					</g:if>
				
					<g:if test="${statusBInstance?.gftMsgBs}">
						<dt><g:message code="statusB.gftMsgBs.label" default="Gft Msg Bs" /></dt>
						
							<g:each in="${statusBInstance.gftMsgBs}" var="g">
							<dd><g:link controller="gftMsgB" action="show" id="${g.id}">${g?.encodeAsHTML()}</g:link></dd>
							</g:each>
						
					</g:if>
				
					<g:if test="${statusBInstance?.wireDataBs}">
						<dt><g:message code="statusB.wireDataBs.label" default="Wire Data Bs" /></dt>
						
							<g:each in="${statusBInstance.wireDataBs}" var="w">
							<dd><g:link controller="wireDataB" action="show" id="${w.id}">${w?.encodeAsHTML()}</g:link></dd>
							</g:each>
						
					</g:if>
				
				</dl>

				<g:form class="block-800px center">
					<g:hiddenField name="id" value="${statusBInstance?.id}" />
					<div class="form-actions">
						<g:link class="btn  btn-primary" action="edit" id="${statusBInstance?.id}">
							<i class="icon-pencil icon-white"></i>
							<g:message code="default.button.edit.label" default="Edit" />
						</g:link>
						<g:form class="form-horizontal" action="edit" id="${statusBInstance?.id}" >
							<g:hiddenField name="version" value="${statusBInstance?.version}" />
							<button type="submit" class="btn btn-danger" name="_action_delete" formnovalidate onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
								<i class="icon-trash icon-white"></i>
								<g:message code="default.button.delete.label" default="Delete" />
							</button>							
						</g:form>
					</div>
				</g:form>

			</div>

		</div>
	</body>
</html>