grails-app/domain/com/unionbank/rwo/management/BeneficiaryB.groovy
package com.unionbank.rwo.management

import groovy.transform.ToString

@ToString (ignoreNulls = true, includeNames=false, includeFields=true, 
	includePackage = false, includeSuper=false,
	excludes="ssoId,bnfciryName,addrLineOne,addrLineTwo,addrLineThree,city,state,postalCd,country,createDt,updateDt")
class BeneficiaryB {

	Long bnfciryId
	String cifNbr
	String ssoId
	String bnfciryName
	String acctNbr
	String addrLineOne
	String addrLineTwo
	String addrLineThree
	String city
	String state
	String postalCd
	String country
	Character actvFlg
	Date createDt
	Date updateDt
	BankInfoB bank_Info

	static hasMany = [wireDataBs: WireDataB]
	static belongsTo = [BankInfoB]

	static mapping = {
		id column: "BNFCIRY_ID", name: "bnfciryId"
		version false
		table "BENEFICIARY_B"
	}

	static constraints = {
		cifNbr maxSize: 12
		ssoId maxSize: 32
		bnfciryName nullable: true
		acctNbr nullable: true, maxSize: 24
		addrLineOne nullable: true
		addrLineTwo nullable: true
		addrLineThree nullable: true
		city nullable: true
		state nullable: true, maxSize: 128
		postalCd nullable: true, maxSize: 24
		country nullable: true, maxSize: 128
		actvFlg maxSize: 1
	}
	
	def getId(){
		bnfciryId
	}
}

grails-app/domain/com/unionbank/rwo/management/WireDataB.groovy
package com.unionbank.rwo.management

class WireDataB {

	Long transactionId
	Long sequenceNbr
	String cifNbr
	String ssoId
	String sendAccountNumber
	String sendAccountCode
	String sendAccountDesc
	String channelType
	BigDecimal trnsfrAmt
	BigDecimal transactionFee
	Date trnsfrDt
	Date deliveryDt
	Date trnsfrUpdtDt
	Date gftResponseDt
	String obiComment
	String purposeOfWire
	BigDecimal gftTransId
	BankInfoB bank_Info
	StatusB status
	BeneficiaryB bnfciry

	static hasMany = [gftMsgBs: GftMsgB]
	static belongsTo = [BankInfoB, BeneficiaryB, StatusB]

	static mapping = {
		id column: "TRANSACTION_ID", name: "transactionId"
		version false
		table "WIRE_DATA_B"
		status column: "status_cd"
	}

	static constraints = {
		sequenceNbr nullable: true
		cifNbr maxSize: 12
		ssoId maxSize: 32
		sendAccountNumber nullable: true, maxSize: 32
		sendAccountCode nullable: true, maxSize: 12
		sendAccountDesc nullable: true, maxSize: 140
		channelType maxSize: 5
		trnsfrAmt scale: 4
		transactionFee scale: 4
		deliveryDt nullable: true
		gftResponseDt nullable: true
		obiComment nullable: true, maxSize: 140
		purposeOfWire nullable: true, maxSize: 140
		gftTransId nullable: true
	}
	
	Long getId(){
		transactionId
	}
}

grails-app/controllers/com/unionbank/rwo/management/WireDataBController.groovy
package com.unionbank.rwo.management

import org.springframework.dao.DataIntegrityViolationException
import org.springframework.dao.DuplicateKeyException
import grails.plugins.springsecurity.Secured

@Secured(['IS_AUTHENTICATED_FULLY'])
class WireDataBController {

	def wireDataBService

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

	def revisions = {
		params.max = Math.min(params.int('max') ?: 10, 20)
		params.offset = params.int('offset') ?: 0
		params.order = "desc"
		// TODO: obtaining size should be improved
		def wireDataBRevisionInstanceTotal = WireDataB.findAllRevisions().size()
		def audited = WireDataB.class.isAnnotationPresent( org.hibernate.envers.Audited.class )
		render(view: 'revisions', model: [wireDataBRevisionInstanceList: WireDataB.findAllRevisions(params).reverse(), wireDataBRevisionInstanceTotal: wireDataBRevisionInstanceTotal, audited: audited])
	}
	
    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
		def audited = WireDataB.class.isAnnotationPresent( org.hibernate.envers.Audited.class )
        [wireDataBInstanceList: WireDataB.list(params), wireDataBInstanceTotal: WireDataB.count(), audited: audited]
    }
	
	def show(java.lang.Long id) {
		def wireDataBInstance = WireDataB.get(id)
		if (!wireDataBInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), id])
			redirect(action: "list")
			return
		}
		def audited = WireDataB.class.isAnnotationPresent( org.hibernate.envers.Audited.class )
		[wireDataBInstance: wireDataBInstance, audited: audited]
	}

/*
    def create() {
		def audited = WireDataB.class.isAnnotationPresent( org.hibernate.envers.Audited.class )
        [wireDataBInstance: wireDataBService.create(params), audited: audited]
    }

    def save() {
		def wireDataBInstance
		try{
			wireDataBInstance = wireDataBService.save(params)
		} catch (GenericSaveException gsx){
			render(view: "create", model: [wireDataBInstance: wireDataBInstance])
			return
		}
		flash.message = message(code: 'default.created.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), wireDataBInstance.id])
		redirect(action: "show", id: wireDataBInstance.id)
    }

    def edit(java.lang.Long id) {
		def wireDataBInstance
		try{
			wireDataBInstance = wireDataBService.edit(id)
		} catch (GenericSaveException gsx){
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), id])
			redirect(action: "list")
			return
		}
		def audited = WireDataB.class.isAnnotationPresent( org.hibernate.envers.Audited.class )
		[wireDataBInstance: wireDataBInstance, audited: audited]
    }

    def update(java.lang.Long id, Long version) {
		def wireDataBInstance
		try{
			wireDataBInstance = wireDataBService.update(id, version, params)
		} catch (GenericSaveException gsx) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), id])
			redirect(action: "list")
			return
		} catch (GenericVersionMismatchException gsx) {
			wireDataBInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
				[message(code: 'wireDataB.label', default: 'WireDataB')] as Object[],
						"Another user has updated this WireDataB while you were editing")
			  render(view: "edit", model: [wireDataBInstance: wireDataBInstance])
			  return
		} catch (GenericSaveException gsx){
			render(view: "edit", model: [wireDataBInstance: wireDataBInstance])
			return
		}
		flash.message = message(code: 'default.updated.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), wireDataBInstance.id])
		redirect(action: "show", id: wireDataBInstance.id)
    }

    def delete(java.lang.Long id) {
		try{
			def wireDataBInstance = wireDataBService.delete(id)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), id])
			redirect(action: "list")
		} catch (GenericNotFoundException e) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), id])
			redirect(action: "list")
			return
		} catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), id])
			redirect(action: "show", id: id)
			return
		}		
    }
	
	def handleDuplicateKeyException(DuplicateKeyException dkx) {
		def wireDataBInstance = new WireDataB(params)
		log.error "DuplicateKeyException ${params.keyName}"
		flash.message = message(code: 'default.duplicate.message', args: [message(code: 'wireDataB.label', default: 'WireDataB'), wireDataBInstance.id])
		render(view: "create", model: [wireDataBInstance: wireDataBInstance])
		return
	}
*/
}

grails-app/views/wireDataB/_form.gsp
// NOTHING to generate

grails-app/views/wireDataB/create.gsp
<%@ page import="com.unionbank.rwo.management.WireDataB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'wireDataB.label', default: 'WireDataB')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.create.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				
			
			<div class="block-800px center">

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info block-800px center">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${wireDataBInstance}">
				<bootstrap:alert class="alert-error block-800px center">
				<ul>
					<g:eachError bean="${wireDataBInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal" action="save" >
						<fieldset>
							<div class="control-group ">
								<label class="control-label" for="${wireDataBInstance?.id}">${wireDataBInstance?.id}</label>
								<div class="controls primary-key-id">
									${wireDataBInstance?.id}
								</div>
							</div>
							<f:all bean="wireDataBInstance"/>
							<div class="form-actions">
								<g:link class="list btn" action="list">
									<i class="icon-arrow-left"></i>
									<g:message code="default.button.cancel.label" default="Cancel" />
								</g:link>
								<button type="submit" class="btn btn-success">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.create.label" default="Create" />
								</button>
							</div>
						</fieldset>
					</g:form>
				</fieldset>
				</div>
			</div>

		</div>
	</body>
</html>

grails-app/views/wireDataB/edit.gsp
<%@ page import="com.unionbank.rwo.management.WireDataB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'wireDataB.label', default: 'WireDataB')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.edit.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
						<g:link class="create btn btn-success intro-entity-create-button" action="create">
							<i class="icon-plus icon-white"></i>
							<span class="hidden-phone"><g:message code="default.create.label" args=" "/> </span><span class="visible-desktop">${entityName}</span>
						</g:link>
					</div>
				</div>				
			
			<div>
				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info block-800px center">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${wireDataBInstance}">
				<bootstrap:alert class="alert-error block-800px center">
				<ul>
					<g:eachError bean="${wireDataBInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal block-800px center" action="edit" id="${wireDataBInstance?.id}" >
						<g:hiddenField name="version" value="${wireDataBInstance?.version}" />
						<fieldset>
							<f:display bean="wireDataBInstance" property="keyName"/>					
							<f:all bean="wireDataBInstance" except="id,keyName"/>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary" name="_action_update">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.update.label" default="Update" />
								</button>
								<button type="submit" class="btn btn-danger" name="_action_delete" formnovalidate onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
									<i class="icon-trash icon-white"></i>
									<g:message code="default.button.delete.label" default="Delete" />
								</button>
								<g:link class="list btn" action="list">
									<i class="icon-arrow-left"></i>
									<g:message code="default.button.cancel.label" default="Cancel" />
								</g:link>
							</div>
						</fieldset>
					</g:form>
				</fieldset>
				</div>
			</div>
		</div>
	</body>
</html>

grails-app/views/wireDataB/list.gsp
<%@ page import="com.unionbank.rwo.management.WireDataB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'wireDataB.label', default: 'WireDataB')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">
				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.list.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
					</div>
				</div>				

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info block-800px center">${flash.message}</bootstrap:alert>
				</g:if>
				<div class="table-responsive">
				<table class="table table-striped table-800px center intro-page-main-data">
					<thead>
						<tr class="intro-page-main-metadata">
						
							<g:sortableColumn property="sequenceNbr" title="${message(code: 'wireDataB.sequenceNbr.label', default: 'Sequence Nbr')}" />
						
							<g:sortableColumn property="cifNbr" title="${message(code: 'wireDataB.cifNbr.label', default: 'Cif Nbr')}" />
						
							<g:sortableColumn property="ssoId" title="${message(code: 'wireDataB.ssoId.label', default: 'Sso Id')}" />
						
							<g:sortableColumn property="sendAccountNumber" title="${message(code: 'wireDataB.sendAccountNumber.label', default: 'Send Account Number')}" />
						
							<g:sortableColumn property="sendAccountCode" title="${message(code: 'wireDataB.sendAccountCode.label', default: 'Send Account Code')}" />
						
							<g:sortableColumn property="sendAccountDesc" title="${message(code: 'wireDataB.sendAccountDesc.label', default: 'Send Account Desc')}" />
						
							<th class="pull-right">Operations</th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${wireDataBInstanceList}" var="wireDataBInstance">
						<tr>
						
							<td>${fieldValue(bean: wireDataBInstance, field: "sequenceNbr")}</td>
						
							<td>${fieldValue(bean: wireDataBInstance, field: "cifNbr")}</td>
						
							<td>${fieldValue(bean: wireDataBInstance, field: "ssoId")}</td>
						
							<td>${fieldValue(bean: wireDataBInstance, field: "sendAccountNumber")}</td>
						
							<td>${fieldValue(bean: wireDataBInstance, field: "sendAccountCode")}</td>
						
							<td>${fieldValue(bean: wireDataBInstance, field: "sendAccountDesc")}</td>
						
							<td class="link text-right intro-entity-button-functions">
									<g:link action="show"
										id="${wireDataBInstance.id}" class="btn btn-success btn-mini intro-entity-button-show">
										<i class="icon-search icon-white"></i><span class="hidden-phone"> Show</span>
									</g:link>
							</td>
						</tr>
						
					</g:each>
					</tbody>
				</table>
				</div>
				<div class="pagination pagination-centered">
					<bootstrap:paginate total="${wireDataBInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

grails-app/views/wireDataB/show.gsp
<%@ page import="com.unionbank.rwo.management.WireDataB" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'wireDataB.label', default: 'WireDataB')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span12">

				<div class="page-header">
					<h1 calss="intro-page-head"><span class="hidden-phone"><g:message code="default.show.label" args=" " /></span> ${entityName}</h1>
					<div class="sub-actions btn-group pull-right intro-page-common-functions-top">
						<a id="intro-testdrive" class="btn btn-inverse intro-testdrive-button" title="Test Drive RWO-A UI"><i class="icon-certificate icon-white"></i></a>
						<g:link class="list btn btn-info intro-entity-list-button" action="list">
							<i class="icon-list icon-white"></i>
							<span class="hidden-phone"><g:message code="default.list.label" args=" "/></span><span class="visible-desktop"> ${entityName}</span>
						</g:link>
						<g:if test="${audited}">
						<g:link class="revisions btn intro-entity-revisions-button" action="revisions">
							<i class="icon-time"></i>
							<span class="visible-desktop">${entityName} </span><span class="hidden-phone"><g:message code="default.revisions.label" args=" "/></span>
						</g:link>
						</g:if>
					</div>
				</div>				

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<dl class="block-800px center">
				
					<g:if test="${wireDataBInstance?.sequenceNbr}">
						<dt><g:message code="wireDataB.sequenceNbr.label" default="Sequence Nbr" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="sequenceNbr"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.cifNbr}">
						<dt><g:message code="wireDataB.cifNbr.label" default="Cif Nbr" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="cifNbr"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.ssoId}">
						<dt><g:message code="wireDataB.ssoId.label" default="Sso Id" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="ssoId"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.sendAccountNumber}">
						<dt><g:message code="wireDataB.sendAccountNumber.label" default="Send Account Number" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="sendAccountNumber"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.sendAccountCode}">
						<dt><g:message code="wireDataB.sendAccountCode.label" default="Send Account Code" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="sendAccountCode"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.sendAccountDesc}">
						<dt><g:message code="wireDataB.sendAccountDesc.label" default="Send Account Desc" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="sendAccountDesc"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.channelType}">
						<dt><g:message code="wireDataB.channelType.label" default="Channel Type" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="channelType"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.trnsfrAmt}">
						<dt><g:message code="wireDataB.trnsfrAmt.label" default="Trnsfr Amt" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="trnsfrAmt"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.transactionFee}">
						<dt><g:message code="wireDataB.transactionFee.label" default="Transaction Fee" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="transactionFee"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.deliveryDt}">
						<dt><g:message code="wireDataB.deliveryDt.label" default="Delivery Dt" /></dt>
						
							<dd><g:formatDate date="${wireDataBInstance?.deliveryDt}" /></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.gftResponseDt}">
						<dt><g:message code="wireDataB.gftResponseDt.label" default="Gft Response Dt" /></dt>
						
							<dd><g:formatDate date="${wireDataBInstance?.gftResponseDt}" /></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.obiComment}">
						<dt><g:message code="wireDataB.obiComment.label" default="Obi Comment" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="obiComment"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.purposeOfWire}">
						<dt><g:message code="wireDataB.purposeOfWire.label" default="Purpose Of Wire" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="purposeOfWire"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.gftTransId}">
						<dt><g:message code="wireDataB.gftTransId.label" default="Gft Trans Id" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="gftTransId"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.bank_Info}">
						<dt><g:message code="wireDataB.bank_Info.label" default="Bank Info" /></dt>
						
							<dd><g:link controller="bankInfoB" action="show" id="${wireDataBInstance?.bank_Info?.id}">${wireDataBInstance?.bank_Info?.encodeAsHTML()}</g:link></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.bnfciry}">
						<dt><g:message code="wireDataB.bnfciry.label" default="Bnfciry" /></dt>
						
							<dd><g:link controller="beneficiaryB" action="show" id="${wireDataBInstance?.bnfciry?.id}">${wireDataBInstance?.bnfciry?.encodeAsHTML()}</g:link></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.gftMsgBs}">
						<dt><g:message code="wireDataB.gftMsgBs.label" default="Gft Msg Bs" /></dt>
						
							<g:each in="${wireDataBInstance.gftMsgBs}" var="g">
							<dd><g:link controller="gftMsgB" action="show" id="${g.id}">${g?.encodeAsHTML()}</g:link></dd>
							</g:each>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.status}">
						<dt><g:message code="wireDataB.status.label" default="Status" /></dt>
						
							<dd><g:link controller="statusB" action="show" id="${wireDataBInstance?.status?.id}">${wireDataBInstance?.status?.encodeAsHTML()}</g:link></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.transactionId}">
						<dt><g:message code="wireDataB.transactionId.label" default="Transaction Id" /></dt>
						
							<dd><g:fieldValue bean="${wireDataBInstance}" field="transactionId"/></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.trnsfrDt}">
						<dt><g:message code="wireDataB.trnsfrDt.label" default="Trnsfr Dt" /></dt>
						
							<dd><g:formatDate date="${wireDataBInstance?.trnsfrDt}" /></dd>
						
					</g:if>
				
					<g:if test="${wireDataBInstance?.trnsfrUpdtDt}">
						<dt><g:message code="wireDataB.trnsfrUpdtDt.label" default="Trnsfr Updt Dt" /></dt>
						
							<dd><g:formatDate date="${wireDataBInstance?.trnsfrUpdtDt}" /></dd>
						
					</g:if>
				
				</dl>

			<g:form class="block-800px center">
				<g:hiddenField name="id" value="${beneficiaryBInstance?.id}" />
				<div class="form-actions">
					<div class="block-800px center">
						<g:link class="list btn" action="list">
							<i class="icon-arrow-left"></i>
							<g:message code="default.button.back.label" default="Back" />
						</g:link>
					</div>
				</div>
			</g:form>

		</div>

		</div>
	</body>
</html>